apiVersion: v1
kind: ResourceQuota
metadata:
  name: enterprise-quota
  namespace: enterprise
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: "128Mi"
    limits.cpu: "500m"
    limits.memory: "256Mi"
    pods: "3"
