apiVersion: v1
kind: ServiceAccount
metadata:
  name: notiflex-api
  namespace: enterprise
  annotations:
    iam.gke.io/gcp-service-account: notiflex-secret-reader@git-ai-ops-practice.iam.gserviceaccount.com
